[tool.black]
line-length = 98  # Adjust line length to your preference
skip-string-normalization = true  # Preserves the original quote style used in the string
target-version = ['py39']  # Target a specific Python version
include = '\.pyi?$'
exclude = '''
/(
    .eggs
  | .git
  | .hg
  | .mypy_cache
  | .tox
  | .venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
