name: CLIENT CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
            **/cypress
          key: ${{ runner.os }}-yarn-${{ hashFiles('client/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          cd client
          yarn install

      - name: Lint
        run: |
          cd client
          yarn lint

      - name: Build
        run: |
          cd client
          yarn build

      - name: Update Browserslist
        run: |
          cd client
          npx update-browserslist-db@latest

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v4
        with:
          working-directory: client
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome

      - name: Test
        run: |
          cd client
          yarn test:ci
